//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comments = new HashSet<Comment>();
            this.Descriptions = new HashSet<Description>();
            this.TagsJunctions = new HashSet<TagsJunction>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> DescId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> RatingId { get; set; }
        public string Ingredients { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual BrandTable BrandTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Description> Descriptions { get; set; }
        public virtual Description Description { get; set; }
        public virtual Image Image { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagsJunction> TagsJunctions { get; set; }
    }
}
